### ISSUE TITLE
Table of contents points to dead link

### ISSUE THREAD

**Issue by bosz** [ARCANEDEV/LaravelSeo#7]
- LaravelSeo Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#

### Description:
Great job developing something to help. But pls, for the documentation, if the links don't work, just comment them or add a text to indicate they don't work. Talking about the links in table of content on read me. They are all dead links.

**Comment by bosz** [comment]
Delivery is Tuesday 23th July 2017.

**Comment by arcanedev-maroc** [comment]
Thanks for your comment.

I've already mentioned it: https://github.com/ARCANEDEV/LaravelSeo/blob/master/README.md#todos
